Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -69,19 +69,19 @@ jobs:
           scp /tmp/mcs.sh $USER@submit-b.hpc.engr.oregonstate.edu:/tmp/mcs.sh
           ssh -tt $USER@submit-b.hpc.engr.oregonstate.edu 
           "
-            source /etc/profile; # makes 'module load' work
+            source /etc/profile; # makes 'module load' work;
             module load slurm; 
-            RES=$(sbatch /tmp/mcs.sh)
-            SJOBID=${RES##*}
-            # wait for gpu job to finish
-            until [[sacct -j $SJOBID | grep COMPLETED] || [sacct -h $SJOBID | grep CANCELLED]]
-            do
-              sleep 5
-            done
-            echo '==== STDOUT ===='
-            cat mcs.out
-            echo '==== STDERR ===='
-            cat mcs.err
-            # check if the build failed/passed
-            if ! cat mcs.out | grep 69420; then exit 404; fi
+            RES=$(sbatch /tmp/mcs.sh);
+            SJOBID=${RES##*};
+            # wait for gpu job to finish;
+            until [[sacct -j $SJOBID | grep COMPLETED] || [sacct -h $SJOBID | grep CANCELLED]];
+            do;
+              sleep 5;
+            done;
+            echo '==== STDOUT ====';
+            cat mcs.out;
+            echo '==== STDERR ====';
+            cat mcs.err;
+            # check if the build failed/passed;
+            if ! cat mcs.out | grep 69420; then exit 404; fi;
           "
