Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -57,10 +57,12 @@ jobs:
           # agent code in this branch explodes
           rm different_scenes/preference_0001_01.json
           python eval.py
+          # will check output for this to confirm success!
+          echo "69420"
           # kill the process keeping the slurm job open
           # if you change the sleep time above, this needs changed too
           pgrep sleep | xargs ps | grep 1e4 | xargs echo | cut -d ' ' -f 1 | xargs kill" > /tmp/mcs.sh
-      - name: launch gpu equipped runner
+      - name: launch gpu slurm build job
         run: |
           # give slurm script to the submit server
           scp /tmp/mcs.sh $USER@submit-b.hpc.engr.oregonstate.edu:/tmp/mcs.sh
@@ -73,5 +75,11 @@ jobs:
             do
               sleep 5
             done
+            echo "==== STDOUT ===="
+            cat mcs.out
+            echo "==== STDERR ===="
+            cat mcs.err
+            # check if the build failed/passed
+            if ! cat mcs.out | grep 69420; then exit 404; fi
           "
 
