Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -65,22 +65,23 @@ jobs:
           pgrep sleep | xargs ps | grep 1e4 | xargs echo | cut -d ' ' -f 1 | xargs kill" > /tmp/mcs_slurm.sh
       - name: make submit script
         run: |
-          printf "#!/bin/bash
-          source /etc/profile # makes 'module load' work
-          module load slurm
-          RES=$(sbatch /tmp/mcs_slurm.sh)
-          SJOBID=${RES##*}
-          # wait for gpu job to finish
-          until [[sacct -j $SJOBID | grep COMPLETED] || [sacct -h $SJOBID | grep CANCELLED]]
-          do
-            sleep 5
-          done
-          echo '==== STDOUT ===='
-          cat mcs.out
-          echo '==== STDERR ===='
-          cat mcs.err
-          # check if the build failed/passed
-          if ! cat mcs.out | grep 69420; then exit 404; fi" > /tmp/mcs_submit.sh
+          printf "
+            source /etc/profile # makes 'module load' work
+            module load slurm
+            RES=$(sbatch /tmp/mcs_slurm.sh)
+            SJOBID=${RES##*}
+            # wait for gpu job to finish
+            until [[sacct -j $SJOBID | grep COMPLETED] || [sacct -h $SJOBID | grep CANCELLED]]
+            do
+              sleep 5
+            done
+            echo '==== STDOUT ===='
+            cat mcs.out
+            echo '==== STDERR ===='
+            cat mcs.err
+            # check if the build failed/passed
+            if ! cat mcs.out | grep 69420; then exit 404; fi
+          " > /tmp/mcs_submit.sh
       - name: submit slurm gpu job
         run: |
           # give slurm script to the submit server
